spring.application.name=demo-post
server.port=8081
<<<<<<< HEAD
=======

>>>>>>> 98cc1b55144f9d9295d9c851d5c4fb5a7a6e06ee
# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2
# Datasource (H2 in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# JPA
spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
spring.jpa.show-sql=true
=======
spring.jpa.show-sql=true
>>>>>>> 98cc1b55144f9d9295d9c851d5c4fb5a7a6e06ee
