spring.application.name=demo-post
server.port=8081
# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2
# Datasource (H2 in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true